allowBuilds:
  '@parcel/watcher': true
  dprint: true
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - dprint
  - esbuild
  - sharp
  - unrs-resolver
